# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Audio Weekly
email: chris@webaudioweekly.com
description: Web Audio Weekly brings you the latest news and links about the Web Audio API, the Web MIDI API and the future of audio on the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.webaudioweekly.com" # the base hostname & protocol for your site
twitter_username: webaudioweekly

# Build settings
markdown: kramdown
